print("Hi, what is your name?")
name = input()
print (f"Hi, {name} . How old are you?")
age = input()
print("Please enter your date of birth")
DOB = input(str())
print("Next, Please enter your address")
address = input(str())
print("Also, what sports do you play?")
sport = input()
print(f"So, your name is {name.capitalize()} , you're {age} years old, born on {DOB} and you live at {address.upper()}.Finally, you like to play {sport.capitalize()}, lovely to meet you!")